// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0l4mj7OzIdq-p8bh9gss2_gQxBrVM4lc',
    appId: '1:94564351976:web:3753185670ffe399442e5d',
    messagingSenderId: '94564351976',
    projectId: 'bisa-51853',
    authDomain: 'bisa-51853.firebaseapp.com',
    storageBucket: 'bisa-51853.firebasestorage.app',
    measurementId: 'G-GY59LNWGKB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJS4uO42KIFUGcDiyhlA7OQa_CbnzL8UA',
    appId: '1:94564351976:android:c9a0d658d93a02b0442e5d',
    messagingSenderId: '94564351976',
    projectId: 'bisa-51853',
    storageBucket: 'bisa-51853.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPhRebMp8W4EqefYuwgy3WVPp3HqAM6Jg',
    appId: '1:94564351976:ios:c867388093b2531b442e5d',
    messagingSenderId: '94564351976',
    projectId: 'bisa-51853',
    storageBucket: 'bisa-51853.firebasestorage.app',
    iosClientId: '94564351976-871e3sn3q3mt5567p3mp10ju7s8g9ljv.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileBisa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPhRebMp8W4EqefYuwgy3WVPp3HqAM6Jg',
    appId: '1:94564351976:ios:c867388093b2531b442e5d',
    messagingSenderId: '94564351976',
    projectId: 'bisa-51853',
    storageBucket: 'bisa-51853.firebasestorage.app',
    iosClientId: '94564351976-871e3sn3q3mt5567p3mp10ju7s8g9ljv.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileBisa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0l4mj7OzIdq-p8bh9gss2_gQxBrVM4lc',
    appId: '1:94564351976:web:f53fa76788d511f5442e5d',
    messagingSenderId: '94564351976',
    projectId: 'bisa-51853',
    authDomain: 'bisa-51853.firebaseapp.com',
    storageBucket: 'bisa-51853.firebasestorage.app',
    measurementId: 'G-2GGKF3RP57',
  );

}